version: '3'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/development/nginx/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "81:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./
      dockerfile: docker/development/php-fpm/Dockerfile
    volumes:
      - ./:/var/www

  php-cli:
    build:
      context: ./
      dockerfile: docker/development/php-cli/Dockerfile
    volumes:
      - ./:/var/www
      - composer:/root/.composer/cache

  postgres:
    image: postgres:14.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: blog
    ports:
      - "54329:5432"

volumes:
  composer:
  postgres:
